import turtle
radius = eval(input("Enter radius for circle : "))
y = radius * 2
turtle.showturtle()
turtle.penup()
turtle.goto(-radius, 0)
turtle.pendown()
turtle.circle(radius)
turtle.penup()
turtle.goto(radius, 0)
turtle.pendown()
turtle.circle(radius)
turtle.penup()
turtle.goto(-radius, -y)
turtle.pendown()
turtle.circle(radius)
turtle.penup()
turtle.goto(radius, -y)
turtle.pendown()
turtle.circle(radius)
turtle.done()
