import turtle
turtle.showturtle()
turtle.penup()
turtle.goto(-45, 0)
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.goto(45, 0)
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.goto(-45, -90)
turtle.pendown()
turtle.circle(45)
turtle.penup()
turtle.goto(45, -90)
turtle.pendown()
turtle.circle(45)
turtle.done()
